name: Publish to Public Repo

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          clean: true

      - name: Copy files and re-init git
        run: |
          TMPDIR=$(mktemp -d)
          rsync -a --exclude='.git' ./ "$TMPDIR"/
          rm -rf ./* .[^.]* ..?*  # ← 安全に中身だけ削除
          rsync -a "$TMPDIR"/ ./
          rm -rf "$TMPDIR"
        
          rm -rf .git
          
          # クリーンな作業フォルダを作成
          mkdir clean_project && cd clean_project
          
          # dotfiles（.github や .gitignore など）も含めてコピー（.git は除外）
          rsync -a --exclude='.git' ../flask_setup_project/ .
          
          git init

          git config user.name "solodev-jp"
          git config user.email "209776260+solodev-jp@users.noreply.github.com"

          # .githubと.gitignoreを明示的に削除
          rm -rf .github .gitignore

          git add .
          git commit --author="solodev-jp <209776260+solodev-jp@users.noreply.github.com>" -m "Initial public commit"

      - name: Push to public repo
        env:
          PAT: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git branch -M main
          git remote add public https://x-access-token:$PAT@github.com/solodev-jp/flask_setup_project.git
          git push public main --force
